version: '1.0'
stages:
  - prepare
  - test
  - build
  - JFrogPublishBuild
steps:
  main_clone:
    title: Cloning main repository..
    stage: prepare
    type: git-clone
    repo: 'addteq-apac/addteq-apac'
    revision: master
    git: bitbucket
  run_unit_tests:
    title: Compile/Unit test
    stage: test
    image: 'maven:3.5.2-jdk-8-alpine'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository test      
  build_app_image:
    title: Building Docker Image
    type: build
    stage: build
    image_name: suhasw91/addteq-apac
    working_directory: ./
    tag: '${{CF_BUILD_TIMESTAMP}}'
    dockerfile: Dockerfile
  JFrogPublishBuild:
  type: jfrog-cli
  arguments:
    JFROG_HOST: swagh.jfrog.io
    JFROG_USER: suhas
    JFROG_ACCESS_TOKEN: 94b1c89c-cd41-4a30-8139-0a2ba1662e4e
    JFROG_CLI_BUILD_NAME: addteq-apac
    JFROG_CLI_BUILD_NUMBER: '${{CF_BUILD_ID}}'
    JFROG_CLI_BUILD_URL: '${{CF_BUILD_URL}}'

