version: '1.0'
stages:
  - prepare
  - test
  - build
  - git_update
steps:
  main_clone:
    title: Cloning main repository..
    stage: prepare
    type: git-clone
    repo: 'addteq-apac/addteq-apac'
    revision: master
    git: bitbucket
  run_unit_tests:
    title: Compile/Unit test
    stage: test
    image: 'maven:3.5.2-jdk-8-alpine'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository test      
  build_app_image:
    title: Building Docker Image
    type: build
    stage: build
    image_name: suhasw91/addteq-apac
    working_directory: ./
    tag: '${{CF_BUILD_TIMESTAMP}}'
    dockerfile: Dockerfile
  git_update:
    title: manifests update in app-config
    type: freestyle
    stage: git_update
    commands:
      - git config user.email swagh@addteq.co.in
      - git config user.name suhasw
      - cat deployment.yaml
      - sed -i 's+suhasw91/addteq-apac*+suhasw91/addteq-apac:${{CF_BUILD_TIMESTAMP}}+g' ./manifests/deployment.yaml
      - cat deployment.yaml
      - git add .
      - git commit -m "Done by codefresh CI pipeline stage manifest update: ${{CF_PULL_REQUEST_ID}}"
      - git push https://suhasw@bitbucket.org/suhasw/app-config.git HEAD:main