version: '1.0'
stages:
  - prepare
  - test
  - build
steps:
  main_clone:
    title: Cloning main repository..
    stage: prepare
    type: git-clone
    repo: 'addteq-apac/addteq-apac'
    revision: master
    git: bitbucket
  run_unit_tests:
    title: Unit test
    stage: test
    image: node:8.16
    commands:
      - yarn install
      - yarn test
    environment:
      - CI=true
  build_app_image:
    title: Building Docker Image
    type: build
    stage: build
    image_name: suhasw91/addteq-apac
    working_directory: ./
    tag: '${{CF_BUILD_TIMESTAMP}}'
    dockerfile: Dockerfile
  